Quest 11
yogadeveloper/reduxPub pull request #1
Opened 2020-10-31 15:27 UTC by yogadeveloper

2020-11-01 10:02 UTC, index01d requested changes

2020-11-01 10:02 UTC, index01d commented on src/components/shared/Book/SectionList/Section/Section.js
> +    updateChapter({ chapterIndex: chapterIndex });
что делает updateChapter? можно ли проделать всю необходимую обработку в toggleSections?

2020-11-01 10:28 UTC, yogadeveloper commented on src/components/shared/Book/SectionList/Section/Section.js
> +    updateChapter({ chapterIndex: chapterIndex });
updateChapter проверяет выполнены ли все секции. Если выполнены, то глава, в которой содержится эта секция, также становится выполненной. Если хотя бы одна секция не выполнена, то и глава также помечается невыполненной.

Я не понял как сделать такую проверку в toggleSection, потому что reducer сначала должен выполнится, чтобы состояние обновилось, а только после обновления я могу получить последнее состояние, чтобы сделать проверку.

Я уже начал смотреть в Redux Thunk , но не стал заморачиваться и просто добавил еще один редьюсер.

2020-11-02 19:52 UTC, index01d approved these changes

2020-11-13 08:37 UTC, merged